import { Author } from "next/dist/lib/metadata/types/metadata-types"

const isDev = process.env.VERCEL_ENV === "development"
const isPrev = process.env.VERCEL_ENV === "preview"

export const BASE_URL = isDev
  ? "http://localhost:3000"
  : isPrev
  ? `https://${process.env.VERCEL_URL || "localhost:3000"}`
  : "https://CopyFromURL.com"

export const baseSiteConfig = {
  name: "Copy from URL",
  url: BASE_URL,
  ogImage: `${BASE_URL}/public/og.png`,
  creator: "Keisuke Nagakawa",
  authors: ["Keisuke Nagakawa"] as Author[],
  publisher: "Amunzen Inc.",
}
export const siteConfig = {
  ...baseSiteConfig,
  description: {
    da: "Kopiér al tekst fra en URL",
    de: "Kopiere den gesamten Text von einer URL",
    en: "Copy all text from a URL",
    es: "Copia todo el texto de una URL",
    fr: "Copiez tout le texte d'une URL",
    it: "Copia tutto il testo da un URL",
    nl: "Kopieer alle tekst van een URL",
    pt: "Copie todo o texto de um URL",
    ru: "Скопируйте весь текст с URL",
    sv: "Kopiera all text från en URL",
    zh: "从URL复制所有文本",
    ja: "ウェブページのテキストを簡単に抽出",
  },
  keywords: {
    da: [
      "URL kopi",
      "udklipsholder værktøj",
      "websideindhold",
      "online værktøj",
      "indholdsekstraktor",
      "kopiér webstedstekst",
      "web scraper",
      "indholdskopimaskine",
      "URL indholdsekstraktor",
      "udklipsholder assistent",
      "kopiér tekst fra URL",
      "webindholdskopimaskine",
      "websidetekstkopi",
      "ekstrahér tekst fra URL",
      "URL tekstekstraktor",
      "websidekopimaskine",
      "kopiér webstedsindhold",
      "udklipsholder indholdsekstraktor",
      "kopiér online tekst",
      "webindholdsværktøj",
      "kopiér indholdsværktøj",
      "ekstraktor værktøj",
      "URL indholdskopi",
      "kopiér webtekst",
      "online indholdskopimaskine",
      "tekstkopimaskine",
      "webtekstekstraktor",
      "URL kopi",
      "websidekopiværktøj",
      "indholdskopi assistent",
      "webindholds udklipsholder",
      "webstedstekstkopimaskine",
      "URL tekstkopi",
      "indholdsekstraktionsværktøj",
      "websideindholdsværktøj",
      "webindholdsekstraktion",
      "URL indholdsværktøj",
      "ekstraktor assistent",
      "kopiér online indhold",
      "webindholdsekstraktionsværktøj",
      "indholdskopiværktøj",
      "webindhold assistent",
      "online tekstkopi",
      "webtekstkoppimaskine",
      "webindholdsskærer",
      "udklipsholder ekstraktion",
    ],
    de: [
      "URL-Kopie",
      "Zwischenablage-Tool",
      "Webseiteninhalt",
      "Online-Tool",
      "Inhaltsextraktor",
      "Website-Text kopieren",
      "Web-Scraper",
      "Inhaltskopierer",
      "URL-Inhaltsextraktor",
      "Zwischenablage-Assistent",
      "Text von URL kopieren",
      "Webinhaltskopierer",
      "Webseiten-Textkopie",
      "Text von URL extrahieren",
      "URL-Text-Extraktor",
      "Webseitenkopierer",
      "Website-Inhalt kopieren",
      "Zwischenablage-Inhaltsextraktor",
      "Online-Text kopieren",
      "Webinhaltstool",
      "Inhaltstool kopieren",
      "Extraktor-Tool",
      "URL-Inhaltskopie",
      "Webtext kopieren",
      "Online-Inhaltskopierer",
      "Textkopierer",
      "Webtext-Extraktor",
      "URL-Kopierer",
      "Webseitenkopierwerkzeug",
      "Inhaltskopie-Assistent",
      "Webinhalt-Zwischenablage",
      "Website-Textkopierer",
      "URL-Textkopie",
      "Inhaltsextraktionswerkzeug",
      "Webseiteninhaltstool",
      "Webinhaltsextraktion",
      "URL-Inhaltstool",
      "Extraktor-Assistent",
      "Online-Inhalt kopieren",
      "Webextraktionswerkzeug",
      "Inhaltskopie-Dienstprogramm",
      "Webinhalt-Assistent",
      "Online-Textkopie",
      "Webtextkopierer",
      "Webinhalt-Scraper",
      "Zwischenablage-Extraktion",
    ],
    en: [
      "URL copy",
      "clipboard tool",
      "webpage content",
      "online tool",
      "content extractor",
      "copy website text",
      "web scraper",
      "content copier",
      "URL content extractor",
      "clipboard assistant",
      "copy text from URL",
      "web content copier",
      "web page text copy",
      "extract text from URL",
      "URL text extractor",
      "web page copier",
      "copy site content",
      "clipboard content extractor",
      "copy online text",
      "web content tool",
      "copy content tool",
      "extractor tool",
      "URL content copy",
      "copy web text",
      "online content copier",
      "text copier",
      "web text extractor",
      "URL copier",
      "webpage copy tool",
      "content copy assistant",
      "web content clipboard",
      "site text copier",
      "URL text copy",
      "content extraction tool",
      "webpage content tool",
      "web content extraction",
      "URL content tool",
      "extractor assistant",
      "copy online content",
      "web extraction tool",
      "content copy utility",
      "web content assistant",
      "online text copy",
      "web text copier",
      "web content scraper",
      "clipboard extraction",
    ],
    es: [
      "copia de URL",
      "herramienta de portapapeles",
      "contenido de la página web",
      "herramienta en línea",
      "extractor de contenido",
      "copiar texto del sitio web",
      "raspador web",
      "copiadora de contenido",
      "extractor de contenido de URL",
      "asistente de portapapeles",
      "copiar texto de URL",
      "copiador de contenido web",
      "copia de texto de la página web",
      "extraer texto de URL",
      "extractor de texto de URL",
      "copiadora de páginas web",
      "copiar contenido del sitio",
      "extractor de contenido del portapapeles",
      "copiar texto en línea",
      "herramienta de contenido web",
      "herramienta de copia de contenido",
      "herramienta de extracción",
      "copia de contenido de URL",
      "copiar texto web",
      "copiadora de contenido en línea",
      "copiadora de texto",
      "extractor de texto web",
      "copiadora de URL",
      "herramienta de copia de páginas web",
      "asistente de copia de contenido",
      "portapapeles de contenido web",
      "copiadora de texto del sitio",
      "copia de texto de URL",
      "herramienta de extracción de contenido",
      "herramienta de contenido de páginas web",
      "extracción de contenido web",
      "herramienta de contenido de URL",
      "asistente de extracción",
      "copiar contenido en línea",
      "herramienta de extracción web",
      "utilidad de copia de contenido",
      "asistente de contenido web",
      "copia de texto en línea",
      "copiadora de texto web",
      "raspador de contenido web",
      "extracción de portapapeles",
    ],
    fr: [
      "copie d'URL",
      "outil de presse-papiers",
      "contenu de la page web",
      "outil en ligne",
      "extracteur de contenu",
      "copier le texte du site web",
      "grattoir web",
      "copieur de contenu",
      "extracteur de contenu d'URL",
      "assistant de presse-papiers",
      "copier le texte de l'URL",
      "copieur de contenu web",
      "copie de texte de la page web",
      "extraire le texte de l'URL",
      "extracteur de texte URL",
      "copieur de page web",
      "copier le contenu du site",
      "extracteur de contenu du presse-papiers",
      "copier le texte en ligne",
      "outil de contenu web",
      "outil de copie de contenu",
      "outil d'extraction",
      "copie de contenu URL",
      "copier le texte web",
      "copieur de contenu en ligne",
      "copieur de texte",
      "extracteur de texte web",
      "copieur d'URL",
      "outil de copie de page web",
      "assistant de copie de contenu",
      "presse-papiers de contenu web",
      "copieur de texte du site",
      "copie de texte URL",
      "outil d'extraction de contenu",
      "outil de contenu de page web",
      "extraction de contenu web",
      "outil de contenu URL",
      "assistant d'extraction",
      "copier le contenu en ligne",
      "outil d'extraction web",
      "utilitaire de copie de contenu",
      "assistant de contenu web",
      "copie de texte en ligne",
      "copieur de texte web",
      "grattoir de contenu web",
      "extraction de presse-papiers",
    ],
    it: [
      "copia URL",
      "strumento di appunti",
      "contenuto della pagina web",
      "strumento online",
      "estrattore di contenuti",
      "copia testo del sito web",
      "web scraper",
      "copiatore di contenuti",
      "estrattore di contenuti URL",
      "assistente per appunti",
      "copia testo da URL",
      "copiatore di contenuti web",
      "copia testo della pagina web",
      "estrarre testo da URL",
      "estrattore di testo URL",
      "copiatore di pagine web",
      "copia contenuto del sito",
      "estrattore di contenuti degli appunti",
      "copia testo online",
      "strumento per contenuti web",
      "strumento per copia contenuti",
      "strumento estrattore",
      "copia contenuti URL",
      "copia testo web",
      "copiatore di contenuti online",
      "copiatore di testi",
      "estrattore di testi web",
      "copiatore di URL",
      "strumento per la copia delle pagine web",
      "assistente per la copia dei contenuti",
      "appunti di contenuti web",
      "copiatore di testi del sito",
      "copia testi URL",
      "strumento di estrazione dei contenuti",
      "strumento per contenuti della pagina web",
      "estrazione di contenuti web",
      "strumento per contenuti URL",
      "assistente estrattore",
      "copia contenuti online",
      "strumento di estrazione web",
      "utilità di copia dei contenuti",
      "assistente di contenuti web",
      "copia testo online",
      "copiatore di testi web",
      "web scraper di contenuti",
      "estrazione degli appunti",
    ],
    nl: [
      "URL kopie",
      "klembord tool",
      "webpagina-inhoud",
      "online tool",
      "inhoudsextractor",
      "kopieer website tekst",
      "web scraper",
      "inhoudskopieerapparaat",
      "URL-inhoudsextractor",
      "klembord assistent",
      "kopieer tekst van URL",
      "webinhoudskopieerapparaat",
      "kopie van webpagina-tekst",
      "tekst uit URL extraheren",
      "URL-tekstrextractor",
      "webpagina-kopieerapparaat",
      "kopieer site-inhoud",
      "klembord inhoudsextractor",
      "kopieer online tekst",
      "webinhoudstool",
      "inhoudskopietool",
      "extractortool",
      "URL-inhoudskopie",
      "kopieer webtekst",
      "online inhoudskopieerapparaat",
      "tekstkopieerapparaat",
      "webtekstrextractor",
      "URL kopieerapparaat",
      "webpagina-kopieertool",
      "inhoudskopie-assistent",
      "webinhoudsklembord",
      "site tekst kopieerapparaat",
      "URL tekst kopie",
      "inhoudsextractietool",
      "webpagina-inhoudstool",
      "webinhoudsextractie",
      "URL-inhoudstool",
      "extractorassistent",
      "kopieer online inhoud",
      "webextractietool",
      "inhoudskopie utility",
      "webinhoud assistent",
      "online tekst kopie",
      "webtekst kopieerapparaat",
      "webinhoud scraper",
      "klembord extractie",
    ],
    pt: [
      "cópia de URL",
      "ferramenta de área de transferência",
      "conteúdo da página web",
      "ferramenta online",
      "extrator de conteúdo",
      "copiar texto do site",
      "raspador web",
      "copiadora de conteúdo",
      "extrator de conteúdo de URL",
      "assistente de área de transferência",
      "copiar texto de URL",
      "copiador de conteúdo web",
      "cópia de texto da página web",
      "extrair texto de URL",
      "extrator de texto de URL",
      "copiadora de páginas web",
      "copiar conteúdo do site",
      "extrator de conteúdo da área de transferência",
      "copiar texto online",
      "ferramenta de conteúdo web",
      "ferramenta de cópia de conteúdo",
      "ferramenta de extração",
      "cópia de conteúdo de URL",
      "copiar texto web",
      "copiadora de conteúdo online",
      "copiadora de texto",
      "extrator de texto web",
      "copiadora de URL",
      "ferramenta de cópia de páginas web",
      "assistente de cópia de conteúdo",
      "área de transferência de conteúdo web",
      "copiadora de texto do site",
      "cópia de texto de URL",
      "ferramenta de extração de conteúdo",
      "ferramenta de conteúdo de página web",
      "extração de conteúdo web",
      "ferramenta de conteúdo de URL",
      "assistente de extração",
      "copiar conteúdo online",
      "ferramenta de extração web",
      "utilitário de cópia de conteúdo",
      "assistente de conteúdo web",
      "cópia de texto online",
      "copiadora de texto web",
      "raspador de conteúdo web",
      "extração de área de transferência",
    ],
    ru: [
      "копирование URL",
      "инструмент буфера обмена",
      "содержимое веб-страницы",
      "онлайн-инструмент",
      "экстрактор контента",
      "копировать текст сайта",
      "веб-скрепер",
      "копировщик контента",
      "экстрактор содержимого URL",
      "помощник буфера обмена",
      "копировать текст с URL",
      "копировщик веб-контента",
      "копия текста веб-страницы",
      "извлечение текста из URL",
      "экстрактор текста URL",
      "копировщик веб-страниц",
      "копировать содержимое сайта",
      "экстрактор содержимого буфера обмена",
      "копировать текст онлайн",
      "инструмент веб-контента",
      "инструмент копирования содержимого",
      "инструмент экстрактора",
      "копирование содержимого URL",
      "копировать веб-текст",
      "копировщик онлайн-контента",
      "копировщик текста",
      "экстрактор веб-текста",
      "копировщик URL",
      "инструмент копирования веб-страниц",
      "помощник по копированию контента",
      "буфер обмена веб-контента",
      "копировщик текста сайта",
      "копия текста URL",
      "инструмент извлечения содержимого",
      "инструмент содержимого веб-страницы",
      "извлечение веб-контента",
      "инструмент содержимого URL",
      "помощник экстрактора",
      "копировать онлайн-контент",
      "инструмент извлечения веб-контента",
      "инструмент копирования содержимого",
      "помощник веб-контента",
      "копия текста онлайн",
      "копировщик веб-текста",
      "веб-скрепер контента",
      "извлечение буфера обмена",
    ],
    sv: [
      "URL-kopia",
      "urklippsverktyg",
      "webbsidainnehåll",
      "onlinetool",
      "innehållsextraktor",
      "kopiera webbplatsens text",
      "webbskrapa",
      "innehållskopierare",
      "URL-innehållsextraktor",
      "urklippsassistent",
      "kopiera text från URL",
      "webbinnehållskopierare",
      "webbsidatextkopia",
      "extrahera text från URL",
      "URL-textextraktor",
      "webbsidkopiator",
      "kopiera webbplatsens innehåll",
      "urklippsinnehållsextraktor",
      "kopiera online-text",
      "webbinnehållsverktyg",
      "kopiera innehållsverktyg",
      "extraktorverktyg",
      "URL-innehållskopia",
      "kopiera webbtext",
      "online innehållskopierare",
      "textkopiator",
      "webbtextextraktor",
      "URL-kopiator",
      "webbsidkopieringsverktyg",
      "innehållskopieringsassistent",
      "webbinnehållsurklipp",
      "webbplatsens textkopiator",
      "URL-textkopia",
      "innehållsextraktionsverktyg",
      "webbsidainnehållsverktyg",
      "webbinnehållsextraktion",
      "URL-innehållsverktyg",
      "extraktorassistent",
      "kopiera online-innehåll",
      "webbextraktionsverktyg",
      "innehållskopieringsverktyg",
      "webbinnehållsassistent",
      "online textkopia",
      "webbtextkopiator",
      "webbinnehållsskrapa",
      "urklippsextraktion",
    ],
    zh: [
      "URL复制",
      "剪贴板工具",
      "网页内容",
      "在线工具",
      "内容提取器",
      "复制网站文本",
      "网页抓取工具",
      "内容复制器",
      "URL内容提取器",
      "剪贴板助手",
      "从URL复制文本",
      "网页内容复制器",
      "网页文本复制",
      "从URL提取文本",
      "URL文本提取器",
      "网页复制器",
      "复制站点内容",
      "剪贴板内容提取器",
      "复制在线文本",
      "网页内容工具",
      "复制内容工具",
      "提取器工具",
      "URL内容复制",
      "复制网页文本",
      "在线内容复制器",
      "文本复制器",
      "网页文本提取器",
      "URL复制器",
      "网页复制工具",
      "内容复制助手",
      "网页内容剪贴板",
      "站点文本复制器",
      "URL文本复制",
      "内容提取工具",
      "网页内容工具",
      "网页内容提取",
      "URL内容工具",
      "提取助手",
      "复制在线内容",
      "网页提取工具",
      "内容复制实用程序",
      "网页内容助手",
      "在线文本复制",
      "网页文本复制器",
      "网页内容抓取工具",
      "剪贴板提取",
    ],
    ja: [
      "URLコピー",
      "クリップボードツール",
      "ウェブページ内容",
      "オンラインツール",
      "コンテンツ抽出",
      "ウェブサイトのテキストをコピー",
      "ウェブスクレーパー",
      "コンテンツコピー",
      "URL内容抽出",
      "クリップボードアシスタント",
      "URLからテキストをコピー",
      "ウェブコンテンツコピー",
      "ウェブページのテキストコピー",
      "URLからテキストを抽出",
      "URLテキスト抽出",
      "ウェブページコピー",
      "サイトの内容をコピー",
      "クリップボード内容抽出",
      "オンラインテキストをコピー",
      "ウェブコンテンツツール",
      "コンテンツコピーツール",
      "抽出ツール",
      "URL内容コピー",
      "ウェブテキストをコピー",
      "オンラインコンテンツコピー",
      "テキストコピー",
      "ウェブテキスト抽出",
      "URLコピー",
      "ウェブページコピーツール",
      "コンテンツコピーアシスタント",
      "ウェブコンテンツクリップボード",
      "サイトテキストコピー",
      "URLテキストコピー",
      "コンテンツ抽出ツール",
      "ウェブページ内容ツール",
      "ウェブコンテンツ抽出",
      "URLコンテンツツール",
      "抽出アシスタント",
      "オンラインコンテンツコピー",
      "ウェブ抽出ツール",
      "コンテンツコピー",
      "ウェブコンテンツアシスタント",
      "オンラインテキストコピー",
      "ウェブテキストコピー",
      "ウェブコンテンツスクレーパー",
      "クリップボード抽出",
    ],
  },
}

export type SiteConfig = typeof siteConfig
